name: Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t demo-app .

    - name: List images
      run: docker images